server:
  port: 8089
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:9091/
          predicates:
          - Path=/products/**
          filters:
            - AuthenticationFilter

        - id: account-service
          uri: http://account-service:8081/
#          uri: http://localhost:30200/
          predicates:
          - Path=/accounts/**
          filters:
          - AuthenticationFilter

        - id: order-service
          uri: http://order-service:9097/
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter

jwt:
  secret: ${SIGN_KEY:WRONG-SECRET}
  validity: 60
  authDisabled: true