apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deployment
  labels:
    app: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
      - name: bank
        image: syilma/bank-service:v2
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080 # port to access the app in the container 
        env: #setting enviromental variable for the container
          - name: token
            valueFrom:
              secretKeyRef:
                name: myvault
                key: SIGN_KEY
          - name: MY_SERVICE_KEY
            valueFrom:
                secretKeyRef:
                  name: myvault
                  key: BANK_SERVICE_KEY
         

---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  selector:
    app: bank
  # type: NodePort # LoadBalancer for or NodePort external service
  ports:
    - protocol: TCP
      port: 9094 # port to access the pod 
      targetPort: 8080 # must be the same as the containerPort 
      # nodePort: 30100 ## for external service port