apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: syilma/payment-service:v2
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080 # port to access the app in the container 
        env: #setting enviromental variable for the container
          - name: token
            valueFrom:
              secretKeyRef:
                name: myvault
                key: SIGN_KEY
          - name: cc
            valueFrom:
              configMapKeyRef:
                name: paymentmap
                key: cc
          - name: bank
            valueFrom:
              configMapKeyRef:
                name: paymentmap
                key: bank      
          - name: paypal
            valueFrom:
              configMapKeyRef:
                name: paymentmap
                key: paypal 
          - name: MY_SERVICE_KEY   
            valueFrom:
                secretKeyRef:
                  name: myvault
                  key: PAYMENT_SERVICE_KEY
          - name: CREDIT_SERVICE_KEY
            valueFrom:
                secretKeyRef:
                  name: myvault
                  key: CREDIT_SERVICE_KEY
          - name: PAYPAL_SERVICE_KEY
            valueFrom:
                secretKeyRef:
                  name: myvault
                  key: PAYPAL_SERVICE_KEY
          - name: BANK_SERVICE_KEY
            valueFrom:
                secretKeyRef:
                  name: myvault
                  key: BANK_SERVICE_KEY
          - name: ORDER_SERVICE_KEY  
            valueFrom:
                secretKeyRef:
                  name: myvault
                  key: ORDER_SERVICE_KEY
          - name: ACCOUNT_SERVICE_KEY
            valueFrom:
                secretKeyRef:
                  name: myvault
                  key: ACCOUNT_SERVICE_KEY
          - name: SHIPPING_SERVICE_KEY
            valueFrom:
                secretKeyRef:
                  name: myvault
                  key: SHIPPING_SERVICE_KEY
          

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  # type: NodePort # LoadBalancer for or NodePort external service
  ports:
    - protocol: TCP
      port: 9092 # port to access the pod 
      targetPort: 8080 # must be the same as the containerPort 
      # nodePort: 30200 ## for external service port