apiVersion: v1
kind: Secret
metadata:
  name: myvault
type: Opaque
data:
  DB_USER_NAME: cm9vdA== #root
  DB_PASSWORD: cm9vdA== #root
  SIGN_KEY: VE9QLVNFQ1JFVA== #TOP-SECRET
  ACCOUNT_SERVICE_KEY: QUNDT1VOVF9TRVJWSUNFX0tFWQo= #ACCOUNT_SERVICE_KEY
  PRODUCT_SERVICE_KEY: UFJPRFVDVF9TRVJWSUNFX0tFWQo= #PRODUCT_SERVICE_KEY
  ORDER_SERVICE_KEY: T1JERVJfU0VSVklDRV9LRVkK #ORDER_SERVICE_KEY
  PAYMENT_SERVICE_KEY: UEFZTUVOVF9TRVJWSUNFX0tFWQo= #PAYMENT_SERVICE_KEY
  PAYPAL_SERVICE_KEY: UEFZUEFMX1NFUlZJQ0VfS0VZCg== #PAYPAL_SERVICE_KEY
  CREDIT_SERVICE_KEY: Q1JFRElUX1NFUlZJQ0VfS0VZCg== #CREDIT_SERVICE_KEY
  BANK_SERVICE_KEY: QkFOS19TRVJWSUNFX0tFWQo= #BANK_SERVICE_KEY
  STOCK_SERVICE_KEY: U1RPQ0tfU0VSVklDRV9LRVkK #STOCK_SERVICE_KEY
  SHIPPING_SERVICE_KEY: U0hJUFBJTkdfU0VSVklDRV9LRVkK #SHIPPING_SERVICE_KEY