apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-deployment
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - name: shipping
        image: syilma/shipping-service:v2
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080 # port to access the app in the container 
        env: #setting enviromental variable for the container
          - name: token
            valueFrom:
              secretKeyRef:
                name: myvault
                key: SIGN_KEY
          - name: MY_SERVICE_KEY   # Setting Secret key
            valueFrom:
                secretKeyRef:
                  name: myvault
                  key: SHIPPING_SERVICE_KEY               
         

---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  selector:
    app: shipping
  # type: NodePort # LoadBalancer for or NodePort external service
  ports:
    - protocol: TCP
      port: 9096 # port to access the pod 
      targetPort: 8080 # must be the same as the containerPort 
      # nodePort: 30100 ## for external service port